version: '3'
services:
  postgres:
    image: postgres
    container_name: ems-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ems
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: ems-redis
    ports:
      - '6373:6373'
    restart: always
