[build]
builder = "nixpacks"
buildCommand = "npx nx run prisma-schema:generate-types && npx nx run website:build:production"
watchPatterns = ["/apps/website"]

[deploy]
startCommand = "npx nx run prisma-schema:migrate-deploy && npx nx run website:serve:production"
# Remember thay tou need to have endpoints deployed before start using below healthchecks
#healthcheckPath = "/api/health"
#healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
